#!/bin/bash

read -p "Name: " NAME
read -p "Email: " EMAIL
read -p "GitHub username: " GITHUB_USERNAME
read -p "GitHub token: " GITHUB_TOKEN

cat << EOF
[user]
	name = $NAME
	email = $EMAIL
[github]
	user = $GITHUB_USERNAME
	token = $GITHUB_TOKEN
[core]
	editor = vim
[color]
	ui = true
[branch]
	autosetuprebase = always
[alias]
	st = status
	co = checkout
	ci = commit
	br = branch
	review = "!die() { echo >&2 \"$@\"; exit 1; }; f() { [ \"$#\" -eq 2 ] || die \"Usage: git review <branch> <topic>\"; git push origin HEAD:refs/for/$1/$2; }; f"
EOF
